version: '3'
services:
  browserless:
    image: 'ghcr.io/browserless/chromium:latest'
    restart: unless-stopped
    environment:
      - TOKEN=***      - MAX_CONCURRENT=10
      - CONCURRENT_FREE=5
