services:
  browserless:
    image: ghcr.io/browserless/chromium:v2.23.0
    restart: unless-stopped
    ports:
      - "4444:3000"
    environment:
      TOKEN: "browsetoken2026"
      MAX_CONCURRENT: 4
      MAX_WAIT_TIME: 60000
      TIMEOUT: 120000
    coolify:
      domains:
        - "https://browse-lan.0mod.com"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
